# Generated by Django 5.2.9 on 2025-12-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypticapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(blank=True, choices=[('anagram', 'Anagram'), ('container', 'Container'), ('deletion', 'Deletion'), ('hidden', 'Hidden'), ('homophone', 'Homophone'), ('letter_selection', 'Letter selection'), ('reversal', 'Reversal')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator',
            field=models.CharField(max_length=100),
        ),
    ]
