# Generated by Django 5.2.9 on 2025-12-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypticapp', '0002_indicator_indicator_type_alter_indicator_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(blank=True, choices=[('anagram', 'Anagram'), ('container', 'Container'), ('deletion', 'Deletion'), ('hidden', 'Hidden'), ('homophone', 'Homophone'), ('letter_selection', 'Letter Selection'), ('reversal', 'Reversal')], default=None, max_length=50, null=True),
        ),
    ]
