# Generated by Django 5.2.9 on 2025-12-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypticapp', '0004_anagramindicator_containerindicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterselectionindicator',
            name='selection',
            field=models.CharField(blank=True, choices=[('first_letter', 'First letter'), ('first_letters', 'First letter(s)'), ('first_and_last', 'First and last letters'), ('capital', 'Capital letter'), ('either_half', 'Either half'), ('two_letters', 'Two letters'), ('last_letter', 'Last letter'), ('last_letters', 'Last letter(s)'), ('middle_letter', 'Middle letter'), ('middle_letters', 'Middle letter(s)'), ('other', 'Other')], default=None, help_text='Which letter-selection type this indicator refers to', max_length=30, null=True),
        ),
    ]
